-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/Bucket/sql/issues-table.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/bucket__bucket_issues (
  _page_id INT UNSIGNED NOT NULL,
  _index INT UNSIGNED NOT NULL,
  page_name LONGTEXT DEFAULT NULL,
  page_name_sub LONGTEXT DEFAULT NULL,
  bucket LONGTEXT DEFAULT NULL,
  property LONGTEXT DEFAULT NULL,
  type LONGTEXT DEFAULT NULL,
  message LONGTEXT DEFAULT NULL,
  INDEX page_name (
    page_name(255)
  ),
  INDEX page_name_sub (
    page_name_sub(255)
  ),
  INDEX bucket (
    bucket(255)
  ),
  INDEX property (
    property(255)
  ),
  INDEX type (
    type(255)
  ),
  INDEX message (
    message(255)
  ),
  PRIMARY KEY(_page_id, _index)
) DEFAULT CHARSET = utf8mb4;
