-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/Bucket/sql/abstractSchemaChanges/patch-bucket_pages_bucket_name_index.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE INDEX bucket_name ON /*_*/bucket_pages (bucket_name);
