-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/Bucket/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/bucket_pages (
  _page_id INT NOT NULL,
  bucket_name VARCHAR(255) NOT NULL,
  put_hash VARCHAR(255) NOT NULL,
  INDEX bucket_name (bucket_name),
  PRIMARY KEY(_page_id, bucket_name)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/bucket_schemas (
  bucket_name VARCHAR(255) NOT NULL,
  schema_json LONGTEXT NOT NULL,
  PRIMARY KEY(bucket_name)
) /*$wgDBTableOptions*/;
