-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/Bucket/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/bucket_pages (
  _page_id INT NOT NULL,
  bucket_name VARCHAR(255) NOT NULL,
  put_hash VARCHAR(255) NOT NULL,
  PRIMARY KEY(_page_id, bucket_name)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/bucket_schemas (
  bucket_name VARCHAR(255) NOT NULL,
  schema_json LONGTEXT NOT NULL,
  PRIMARY KEY(bucket_name)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/bucket__bucket_message (
  _page_id INT UNSIGNED NOT NULL,
  _index INT UNSIGNED NOT NULL,
  page_name LONGTEXT DEFAULT NULL,
  page_name_sub LONGTEXT DEFAULT NULL,
  bucket LONGTEXT DEFAULT NULL,
  property LONGTEXT DEFAULT NULL,
  type LONGTEXT DEFAULT NULL,
  message LONGTEXT DEFAULT NULL,
  INDEX page_name (
    page_name(255)
  ),
  INDEX page_name_sub (
    page_name_sub(255)
  ),
  INDEX bucket (
    bucket(255)
  ),
  INDEX property (
    property(255)
  ),
  INDEX type (
    type(255)
  ),
  INDEX message (
    message(255)
  ),
  PRIMARY KEY(_page_id, _index)
) DEFAULT CHARSET = utf8mb4;
